# Requires GNU Make

TESTS      = 
TARGETS    = $(TESTS) evoldoer
DIRNAME    = evoldoer

DEPS       = telegraph ecfg scfg hmm handel hsm irrev tree amap seq util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
