# Requires GNU Make

TESTS      = testpiper testcatch testsqrt testlogprob
TARGETS    = $(TESTS)
DIRNAME    = util

DEPS       = newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
