# Requires GNU Make

TESTS      = testtgvar
TARGETS    = $(TESTS)
DIRNAME    = telegraph

DEPS       = scfg hmm seq util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
