#!/usr/bin/perl -w

use strict;
use Carp;

my $usage = "\nUsage: $0 <.tm file> <.tm file>
         Compare 2 transition matrices generated by composeTT.pl.
         (Better than diff because it doesn't care about sorting, etc.)\n";

my $agree = 1;
my @files;

while (@ARGV) {
  my $arg = shift @ARGV;
  if ($arg =~ /^-/) {
    if (($arg eq "-h") || ($arg eq "--help")) { print $usage; exit; }
     else { croak $usage; }
  }
  elsif ($arg =~ /\S+\.tm$/) { push (@files, $arg); }
  else { croak $usage; }
}

unless (scalar (@files) eq 2) { croak $usage; }
my ($file1, $file2) = @files;

my $tm1 = {};
my $tm2 = {};

# read in TM
open (FILE1, "<$file1");
while (<FILE1>) {
  # ignore comments and blank lines
  if (/^;/) { next; }
  unless (/\S+/) { next; }

  chomp();
  s/\s//g;

  if (/(\S+)->(\S+)\{(\S*)\}/) { # allow for prob to be unspecified
    $tm1->{$1}->{$2} = $3;
  } else { warn "Ignoring $_"; }
}
close (FILE1);

open (FILE2, "<$file2");
while (<FILE2>) {
  # ignore comments and blank lines
  if (/^;/) { next; }
  unless (/\S+/) { next; }

  chomp();
  s/\s//g;

  if (/(\S+)->(\S+)\{(\S*)\}/) { # allow for prob to be unspecified
    $tm2->{$1}->{$2} = $3;
  } else { warn "Ignoring $_"; }
}
close (FILE2);

warn "scanning TM1 from $file1...\n";
# 1 to 2 comparison
foreach my $src (keys %$tm1) {
  foreach my $dest (keys %{$tm1->{$src}}) {
    if (exists $tm2->{$src}->{$dest}) {
      if ($tm1->{$src}->{$dest} ne $tm2->{$src}->{$dest}) {
	warn "$src -> $dest: ", $tm1->{$src}->{$dest}, " != ", $tm2->{$src}->{$dest}, "\n";
	$agree = 0;
      }
    } else {
      warn "$src -> $dest: absent in $file2.\n";
      $agree = 0;
    }
  }
}

warn "\nscanning TM2 from $file2...\n";
# now do it the other way around: 2 to 1
foreach my $src (keys %$tm2) {
  foreach my $dest (keys %{$tm2->{$src}}) {
    if (exists $tm1->{$src}->{$dest}) {
      if ($tm2->{$src}->{$dest} ne $tm1->{$src}->{$dest}) {
	$agree = 0;
	warn "$src -> $dest: ", $tm2->{$src}->{$dest}, " != ", $tm1->{$src}->{$dest}, "\n";
      }
    } else {
      $agree = 0;
      warn "$src -> $dest: absent in $file1.\n";
    }
  }
}

if ($agree) {
  # if we haven't croaked, then they match!
  warn "\nTransition matrices match.\n\n";
  exit 0;
}
else {
  warn "\nDon't match.\n\n";
  exit 1;
}
