# Requires GNU Make

TESTS      = testtree testpam
TARGETS    = $(TESTS) bsupp getpam drawpstree eztree reroot getinsertions
DIRNAME    = tree

DEPS       = seq util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
