# Requires GNU Make

TESTS      = testfoldenv testpaircfg testpaircfgdp testsampletraceback testelim
TARGETS    = $(TESTS)
DIRNAME    = scfg

DEPS       = amap hmm seq util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
