# Requires GNU Make

TESTS      = 
TARGETS    = $(TESTS) smdist
DIRNAME    = hsm

DEPS       = hmm tree seq util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
