# Requires GNU Make

TESTS      = 
TARGETS    = $(TESTS) kimono kmeans gsamp seer
DIRNAME    = kimono

DEPS       = hmm tree seq util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
