# Requires GNU Make

TESTS      = 
TARGETS    = $(TESTS) ppswalign ppswtrain dpswalign dpswtrain nwalign swalign
DIRNAME    = psw

DEPS       = hsm tree hmm seq util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
