# Requires GNU Make

TESTS      = teststock
TARGETS    = $(TESTS) wordcount cmpalign cmpfold aligncluster
DIRNAME    = seq

DEPS       = util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
