# Requires GNU Make

TESTS      = dottrack
TARGETS    = $(TESTS)
DIRNAME    = gfx

DEPS       = scfg hmm tree seq util newmat randlib

CCDIR      = $(shell pwd)
SRCDIR     = $(CCDIR)/..

include $(SRCDIR)/make.common
